### ISSUE TITLE
animation on Swift

### ISSUE THREAD

**Issue by OleksiiShulzhenko** [lukapool/LKAWaveCircleProgressBar#3]
"WaveRollingAnimation" does not work on Swift. "ProgressAnimation" works.
I added LKAWaveCircleProgressBar on another controllers collection view with notification.
What could it be?

**Comment by lukapool** [comment]
I tested my code in xcode 8 with swift 3.0 and iOS 10, it's work.

1 i create a LKAWaveCircleProgressBar_Bridging_Header_h 


```
#ifndef LKAWaveCircleProgressBar_Bridging_Header_h
#define LKAWaveCircleProgressBar_Bridging_Header_h

#import "WaveLayer.h"
#import "LKAWaveCircleProgressBar.h"

#endif 

```
2 set target's objective-c bridging header in build Settings
3 add view in a controller's view


```
import UIKit
class ViewController: UIViewController {

    var progressBar:LKAWaveCircleProgressBar!;

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        progressBar = LKAWaveCircleProgressBar();
        progressBar.frame = CGRect(x: 10, y: 10, width: 100, height: 100)
        view.addSubview(progressBar)
    }

    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        progressBar.setProgress(Float(arc4random() % 100) / 100.0, animated: true)
    }
}
```


Can you provide a more specific description of the problem?

**Comment by OleksiiShulzhenko** [comment]
Thank you.
Everything is working.

**Comment by lukapool** [comment]
OK

**Comment by OleksiiShulzhenko** [comment]
Animation of rolling does not work when I present another ViewController and turn back.
`    func setCoverPlayAnimation(index: Int) {
        if currentChart == Player.shared.currentChart {
            if let cellRect = collectionView.layoutAttributesForItem(at: IndexPath(item: index, section: 1))?.frame {
                let coverSize = cellRect.width / 189 * 100 + 2
                let coverRect = CGRect(x: cellRect.minX + cellRect.width / 189 * 44 - 1,
                                       y: cellRect.minY + cellRect.height / 233 * 27 - 1,
                                       width: coverSize,
                                       height: coverSize)
                activityIndicatorView.frame = coverRect
                if Player.shared.isPlaying {
                    BaseViewController.activityIndicatorViewTimer = Timer.scheduledTimer(withTimeInterval: 4, repeats: true, block: { [weak self](timer) in
                        let duration = Player.shared.duration.seconds
                        let currentDuration = Player.shared.currentDuration.seconds
                        let sliderValue = currentDuration / duration
                        let floatValue = Float(sliderValue)
                        
                        self?.activityIndicatorView.setProgress(floatValue, animated: false)
                    })
                } else {
                    BaseViewController.activityIndicatorViewTimer?.invalidate()
                }
            }
        }
    }`

**Comment by OleksiiShulzhenko** [comment]
Animation of rolling does not work when I present another ViewController and turn back.
Present after calling this method.
```swift
    func setCoverPlayAnimation(index: Int) {
        if currentChart == Player.shared.currentChart {
            if let cellRect = collectionView.layoutAttributesForItem(at: IndexPath(item: index, section: 1))?.frame {
                let coverSize = cellRect.width / 189 * 100 + 2
                let coverRect = CGRect(x: cellRect.minX + cellRect.width / 189 * 44 - 1,
                                       y: cellRect.minY + cellRect.height / 233 * 27 - 1,
                                       width: coverSize,
                                       height: coverSize)
                activityIndicatorView.frame = coverRect
                if Player.shared.isPlaying {
                    BaseViewController.activityIndicatorViewTimer = Timer.scheduledTimer(withTimeInterval: 4, repeats: true, block: { [weak self](timer) in
                        let duration = Player.shared.duration.seconds
                        let currentDuration = Player.shared.currentDuration.seconds
                        let sliderValue = currentDuration / duration
                        let floatValue = Float(sliderValue)
                        
                        self?.activityIndicatorView.setProgress(floatValue, animated: false)
                    })
                } else {
                    BaseViewController.activityIndicatorViewTimer?.invalidate()
                }
            }
        }
    }
```

**Comment by lukapool** [comment]
Sorry for this problem.
You can fix this problem by add 

> waveRollingAnim.removedOnCompletion = NO;

 in 

> LKAWaveCircleProgressBar.m  

after line: 177 

```
- (void)addWaveRollingAnimation {
    CABasicAnimation *waveRollingAnim = [CABasicAnimation animationWithKeyPath:@"U"];
    waveRollingAnim.fromValue = @0;
    waveRollingAnim.toValue = @(M_PI * 2);
    waveRollingAnim.repeatCount = HUGE_VALF;
    waveRollingAnim.removedOnCompletion = NO;  // add this code
    waveRollingAnim.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    for (int i = 0; i < self.waves.count; i++) {
        waveRollingAnim.duration = self.waveRollingDuration + (i * 0.3);
        [self.waves[i] addAnimation:waveRollingAnim forKey:@"WaveRollingAnimation"];
    }
}
```

I will try to find a better way to fix this problem tomorrow.

**Comment by OleksiiShulzhenko** [comment]
Thank you for the response.

**Comment by lukapool** [comment]
I decided to use another way to fix this problem.
I added two public method to start or stop wave rolling animation.(already commit)

You can add 
`self?.activityIndicatorView.startWaveRollingAnimation() `
in View Controller's viewWillAppear method

OR  fix this problem by add
`waveRollingAnim.removedOnCompletion = NO;`
like the 5th comment
