### ISSUE TITLE
动画无法播放

### ISSUE THREAD

**Issue by zhangyu-96** [lukapool/LKAWaveCircleProgressBar#4]
你好，我在使用时是静态的，即使我是设置了动画为是的，能帮我检查一下是哪里的问题么？十分感谢！

（void）viewDidLoad { 
[super viewDidLoad]; 
LKAWaveCircleProgressBar * wcView = [[LKAWaveCircleProgressBar alloc] initWithFrame：CGRectMake（62.5,125.5,248.5,248.5）]; 
[wcView setProgress：0.8 animated：YES]; 
wcView.progressAnimationDuration = 0.7; 
[self.view addSubview：wcView]; 
[wcView startWaveRollingAnimation];
}

**Comment by lukapool** [comment]
我刚测试了。是可以的。能发个项目给我看下吗？422366176@qq.com

**Comment by zhangyu-96** [comment]
你好，我已经发送给您了，十分感谢！

**Comment by lukapool** [comment]
startWaveRollingAnimation 调用放在 viewWillAppear 中
